// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function test(code) {
  if (code > 599 || code < 500) {
    if (code === 201 || code === 200) {
      return "good response";
    } else {
      return "the catch all";
    }
  } else if (code > 597 || code < 512) {
    return "bad response";
  } else {
    return "the catch all";
  }
}

var a = "good response";

var b = "bad response";

if (a !== "good response") {
  throw new Error("Assertion Failure. File: gpr_3877_test.res, Line: 26, Col: 0", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

if (b !== "bad response") {
  throw new Error("Assertion Failure. File: gpr_3877_test.res, Line: 27, Col: 0", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

exports.test = test;
exports.a = a;
exports.b = b;
/*  Not a pure module */
