// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("../../lib/js/caml_obj.js");
var Caml_option = require("../../lib/js/caml_option.js");

if (!Caml_obj.equal(Caml_option.nullable_to_opt(""), "")) {
  throw new Error("Assertion Failure. File: gpr_974_test.res, Line: 2, Col: 2", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

if (!Caml_obj.equal(Caml_option.undefined_to_opt(""), "")) {
  throw new Error("Assertion Failure. File: gpr_974_test.res, Line: 3, Col: 2", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

if (!Caml_obj.equal(Caml_option.null_to_opt(""), "")) {
  throw new Error("Assertion Failure. File: gpr_974_test.res, Line: 4, Col: 2", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

/*  Not a pure module */
