// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Js_math = require("../../lib/js/js_math.js");

var match = 1;

if (match !== undefined) {
  if (match !== 1) {
    throw new Error("Assertion Failure. File: gpr_3980_test.res, Line: 15, Col: 7", {
              cause: {
                RE_EXN_ID: "Assertion_failure"
              }
            });
  }
  var match$1 = 1;
  if (match$1 !== 1) {
    if (match$1 !== 2) {
      throw new Error("Assertion Failure. File: gpr_3980_test.res, Line: 13, Col: 9", {
                cause: {
                  RE_EXN_ID: "Assertion_failure"
                }
              });
    }
    Js_math.floor(1);
  }
  
} else {
  throw new Error("Assertion Failure. File: gpr_3980_test.res, Line: 15, Col: 7", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

/*  Not a pure module */
