// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(param) {
  throw new Error("Assertion Failure. File: noassert.res, Line: 1, Col: 14", {
            cause: {
              RE_EXN_ID: "Assertion_failure"
            }
          });
}

function h(param) {
  
}

exports.f = f;
exports.h = h;
/* No side effect */
