// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function f(x) {
  switch (x) {
    case "abcd" :
        return 0;
    case "bcde" :
        return 1;
    default:
      throw new Error("Assertion Failure. File: test_string_case.res, Line: 5, Col: 9", {
                cause: {
                  RE_EXN_ID: "Assertion_failure"
                }
              });
  }
}

exports.f = f;
/* No side effect */
